config/routes.rb
Rails.application.routes.draw do
  get '/todos/lista', to: 'todos#lista'
  resources :todos
  #delete 'todos/:id', to: 'todos#destroy'
  get '/todos', to: 'todos#index'
  get '/todos/new', to: 'todos#new'
  get '/todos/:id/edit', to: 'todos#edit', as: 'edit'
  patch '/todos/:id', to: 'todos#update'
  post '/todos/create', to: 'todos#create'
  delete '/todos/:id', to: 'todos#destroy'

  get '/todos/:id', to: 'todos#show'
  get '/todos/:id/complete', to: 'todos#complete', as: 'complete'


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo.rb
class Todo < ApplicationRecord
  validates :description, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController

    def index
        @todos = Todo.all
    end

    def new
        @todo = Todo.new
    end


    def create
        @todo_Params = Todo.new(todo_params)
        @todo_Params.save
        redirect_to todos_path
    end

    def lista
      
        @todos = Todo.all

    end

    def show

        @todo = Todo.find(params[:id])
    end

    def edit
        @todo = Todo.find(params[:id])
    end

    def update
        @todo = Todo.find(params[:id])
        @todo.update(todo_params)
        redirect_to todos_path
    end

    def destroy
        @todo = Todo.find(params[:id])
        @todo.destroy
        redirect_to todos_path
    end



    def complete

          @todo = Todo.find(params[:id])
          #@todo = Todo.update(params[:completed])
          @todo.completed = true
            #if @todo.completed == false
            #    @todo.completed == true
            #end
          @todo.save
          redirect_to todos_path
    end

    private
    def todo_params
        params.require(:todo).permit(:description, :completed)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-primary">
<a class="navbar-brand" href="#">Rails</a>
<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
  <span class="navbar-toggler-icon"></span>
</button>
<div class="collapse navbar-collapse" id="navbarText">
  <ul class="navbar-nav mr-auto">
    <li class="nav-item active">
      <a class="nav-link" <%= link_to 'Index', todos_path %></a>
    </li>
    <li class="nav-item">
      <a class="nav-link" <%= link_to 'List', todos_lista_path %></a>
    </li>
    <li class="nav-item">
      <a class="nav-link" <%= link_to 'Form', new_todo_path %></a>
    </li>
  </ul>

</div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TodoApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <%= render 'layouts/navbar' %>
  <body>
    <%= yield %>
  </body>
</html>

app/views/todos/_form.html.erb
<h1> Formulario </h1>
<%= form_with  model: @todo, local: true do |f| %>


  <%= f.label :description, "Descripción"%>
  <%= f.text_field :description %>
  </br>
  <%= f.label :completed, "Completed"%>
  <%= f.text_field :completed %>

  </br>
  <%= f.submit "Enviar" %>
<% end %>

app/views/todos/edit.html.erb
<div class="container-fluid py-5 text-center ">

  <%= render 'todos/form' %>
</div>

app/views/todos/index.html.erb
<div class="card">
  <div class="card-body">

        <h1>Descripciones</h1>

        <table class="table">
        <thead>
            <tr>
            <th>Description</th>
            <th>Completed</th>
            <th>Fecha de creacion</th>
            <th>Mostrar</th>
            <th>Editar</th>
            <th>Eliminar</th>
            <th>Completado</th>

            <th colspan="3"></th>
            </tr>
        </thead>

        <tbody>
            <% @todos.each do |todo| %>
            <tr>
                <td><%= todo.description %></td>
                <td><%= todo.completed %></td>
                <td><%= todo.created_at %></td>
                <td><%= link_to "Show", todo_path(todo)%></td>
                <td><%= link_to "Edit", edit_path(todo)%></td>
                <td><%= link_to "Eliminar", todo, method: :delete %></td>
                <td><%= link_to "Completado", complete_path(todo) %></td>
            </tr>
            <% end %>
        </tbody>
        </table>
  </div>
</div>

<%= link_to  'Crear todo', todos_new_path %>
</br>
<%= link_to  'Listar', todos_lista_path %>

app/views/todos/lista.html.erb
<div class="row">
  <div class="col-sm-6">

        <h1>Lista no completados</h1>

        <table class="table">
        <thead>
            <tr>
            <th>Description</th>
            <th>Completed</th>
            <th>Fecha de creacion</th>
            <th colspan="3"></th>
            </tr>
        </thead>

        <tbody>
        <%  @todos.each do |t| %>

          <% if t.completed == false %>
            <tr>
                <td><%= t.description %></td>
                <td><%= t.completed %></td>
                <td><%= t.created_at %></td>
            </tr>
          <% end %>
        <% end %>

        </tbody>
        </table>
  </div>
  <div class="col-sm-6">

        <h1>Lista completados</h1>

        <table class="table">
        <thead>
            <tr>
            <th>Description</th>
            <th>Completed</th>
            <th>Fecha de creacion</th>
            <th colspan="3"></th>
            </tr>
        </thead>

        <tbody>
        <%  @todos.each do |t| %>

          <% if t.completed == true %>
            <tr>
                <td><%= t.description %></td>
                <td><%= t.completed %></td>
                <td><%= t.created_at %></td>
            </tr>
          <% end %>
        <% end %>

        </tbody>
        </table>
  </div>


</div>

app/views/todos/new.html.erb
<div class="container-fluid py-5 text-center ">

  <%= render 'todos/form' %>
</div>

app/views/todos/show.html.erb
<div class="card">
  <div class="card-body">

        <h1>Descripciones</h1>

        <table class="table">
        <thead>
            <tr>
            <th>Description</th>
            <th>Completed</th>
            <th>Fecha de creacion</th>
            <th colspan="3"></th>
            </tr>
        </thead>

        <tbody>
            
            <tr>
                <td><%= @todo.description %></td>
                <td><%= @todo.completed %></td>
                <td><%= @todo.created_at %></td>
            </tr>
           
        </tbody>
        </table>
  </div>
</div>

<%= link_to  'Show', todos_path %>